spring:
  application:
    name: provider-product
  profiles:
    active: dev
 
server:
  port: 8041
  tomcat:
    uri-encoding: UTF-8

eureka:
  environment: ${spring.profiles.active}
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

logging:
  config: classpath:logback-boot.xml
  file:
    path: /Users/yinchuanning/project/logs/demo-springcloud2021/${spring.application.name}

info:
  app:
    environment: ${spring.profiles.active}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8001/eureka/

