spring:
  application:
    name: hystrix-turbine
  profiles:
    active: dev
  boot:
    admin:
      monitor:
        default-timeout: 10000

server:
  port: 8071
  tomcat:
    uri-encoding: UTF-8

eureka:
  environment: ${spring.profiles.active}

logging:
  config: classpath:logback-boot.xml
  file:
    path: /project/logs/demo-springcloud2021/${spring.application.name}

info:
  app:
    environment: ${spring.profiles.active}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

turbine:
  app-config: PROVIDER-USER,PROVIDER-PRODUCT
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")

---
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    instance-id: ${spring.application.name}-01

---
spring:
  config:
    activate:
      on-profile: test
 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    instance-id: ${instanceId:${spring.application.name}-01}

---
spring:
  config:
    activate:
      on-profile: prod
 
eureka:
  client: 
    service-url: 
      defaultZone: ${defaultZone}
  instance:
    instance-id: ${instanceId:${spring.application.name}-01}